### ISSUE TITLE
Add script with Build Action > Embedded Resource

### ISSUE THREAD

**Issue by sireza** [piotrekh/dbup-add-migration#1]
When script is added, this tool should also set the 'Build Action' as 'Embedded Resource' as required by DbUp

p.s. Really useful tool!!

**Comment by piotrekh** [comment]
Hi @sireza, thanks for the kind words :) I will definitely take your suggestion into consideration, but I won't make it a default behaviour because personally I don't embed my scripts in the assembly - I use a custom provider similar to FileSystemScriptProvider, so I need my scripts to have 'Build Action' set to 'Content' (and they are always copied to the output directory). Since I hate having to remember to change the 'Build Action' of every new file (same as you, I guess :) ) I just add this bit of code to the csproj, which makes all the new files from migrations folder be treated as 'Content':

```
<ItemGroup>
    <Content Include="Migrations\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```
Here's what I think I'll do in the next 2 releases to support your use case:
1. In the first release I'll just add a new parameter called 'BuildAction' to the command
2. In the second release I will either introduce a config file so you can set some defaults like the build action so you don't need to type it every time you enter the command (and can also share it with your team if you check it into your repository to have a consistent setup) or check for the first file in migrations folder and use the same build action for the new file. Or maybe even both, I'll think about it.

**Comment by piotrekh** [comment]
@sireza I have just released version 1.1.0 with `-BuildAction` parameter

**Comment by sireza** [comment]
Works great! Thank you!

**Comment by piotrekh** [comment]
@sireza version 1.2.0 introduces support for settings file so you don't have to type `-BuildAction` everytime you generate a new migration. Have fun!
