### ISSUE TITLE
Doesn't seem to survive restarts of visual studio

### ISSUE THREAD

**Issue by ianb1987** [piotrekh/dbup-add-migration#3]
When using this package, it works well enough after initial install but after restarting visual studio, it seems nothing is re-running the init.ps1 script and I get errors (specifically, it thinks I am now talking about EF code first migrations - might it be better to use command names that don't collide with EF?)

**Comment by piotrekh** [comment]
Yeah, I noticed that as well. It's even weirder because sometimes it works as expected, and sometimes it's overwritten by the function from EF migrations. I'm not sure why (maybe the order of powershell scripts initialization by VS?), but I'll create another name for the function so there is no collision. In the meantime, if you have this problem you can prefix the function name with 'dbup-add-migration\' (it should look like 'dbup-add-migration\Add-Migration')

**Comment by ianb1987** [comment]
Ah nice one, thanks for the heads up on the work-around. I'll look at doing that for now 👍 

Nice little package by the way, good time saver

**Comment by piotrekh** [comment]
Hey @ianb1987 check out the new release (it should be visible in nuget package manager in a short time) - I added `Add-DbUpMigration` alias for the command
